---
- name: "Watch for new changelog entries"
  hosts: "localhost"
  sources:
    # Specifies the Nautobot instance, token, and the polling interval.
    - jeffkala.nautobot_eda.nautobot_changelog:
        instance: "https://demo.nautobot.com"
        token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        interval: 1

  # This section defines the rules logic to implement.  In this example its simply capturing all events that have the event.id defined.
  # event.id in this case is the changelog id.
  rules:
    - name: "New changelog created"
      condition: "event.id is defined"
      # Action is triggered if condition is `true`.
      action:
        # For simple examples just print the event as a debug message.
        debug:
